### ISSUE TITLE
Vits-simple-api后台运行正常却无语音返回。

### ISSUE THREAD

**Issue by 4KsTan** [HunterShenSmzh/koishi-plugin-aikanojo#1]
### **问题**：相同设置在[oobaboga-testbot](https://github.com/HunterShenSmzh/koishi-plugin-oobabooga-testbot)运行可以正常输出语音，但是在[aikanojo](https://github.com/HunterShenSmzh/koishi-plugin-aikanojo)里后台正常运行却没返回任何语音也没出现任何BUG

Aikanojo插件版本1.3.1（最新）

Koishi依赖管理：全部最新

KoishiSystem:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500

Binaries:
    Node: 20.12.2
    Yarn: 4.1.1

Koishi:
    Core: 4.18.0
    Console: 5.28.4
    Koishi Desktop: 1.1.3

图一：已选择“同时返回语音与文字（使用内置独立语言接口）”
![1](https://github.com/user-attachments/assets/ba2cb43d-c5ad-4117-a774-772f03bfe663)
图二：vits-simple-api后台正常加载，但是没语音返回。
#还有表情包也无法正常加载
![2](https://github.com/user-attachments/assets/f3dcf534-9466-47e1-b4af-2e800608db32)
图三：在[oobaboga-testbot](https://github.com/HunterShenSmzh/koishi-plugin-oobabooga-testbot)相同设定下可以正常运行（有返回语音）
![3](https://github.com/user-attachments/assets/e4d10854-c4f1-46ee-8ef4-af046c499e78)
图四：Koishi后台也没任何报错
![4](https://github.com/user-attachments/assets/ad528b60-e05c-484c-93ab-878461db10e8)

还请大佬们帮忙看看是哪儿出问题了还是这是插件的BUG。

**Comment by HunterShenSmzh** [comment]
表情是因为沙盒无法加载本地url的图像导致的，你正常接入到其他平台就能看到表情了，语音的话，代码确实有问题，下一版我改一下。

**Comment by 4KsTan** [comment]
> 表情是因为沙盒无法加载本地url的图像导致的，你正常接入到其他平台就能看到表情了，语音的话，代码确实有问题，下一版我改一下。

好的谢谢大佬的效率，这是个很棒的插件👍（的确，表情可以在其他平台看到）

**Comment by 4KsTan** [comment]
佬，请问discord bot发送的是file.mpga而不是发送一段语音是正常的吗？oobaboga-testbot也是只发送file.mpga （抱歉我是个小白）
插件版本:1.3.2
![Screenshot 5](https://github.com/user-attachments/assets/782c7f99-e545-4bde-b4f1-8b9e5dcd8187)

**Comment by HunterShenSmzh** [comment]
这个情况一般来说是和discord的平台对接插件有关系，我这边用的是koishi的音频标准发送，所以和我这边关系不大。

**Comment by 4KsTan** [comment]
> 这个情况一般来说是和discord的平台对接插件有关系，我这边用的是koishi的音频标准发送，所以和我这边关系不大。

好的，谢谢回复
